name: sahibindenmobile
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  flutter_switch: ^0.3.2
  responsive_grid_list: ^1.4.0
  dio: ^5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDecaRegular.ttf
          weight: 400
    - family: Raleway
      fonts:
#        - asset: assets/fonts/RalewayRomanBold.ttf
#          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
#        - asset: assets/fonts/RalewayRomanSemiBold.ttf
#          weight: 600
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
#        - asset: assets/fonts/RalewayRomanMedium.ttf
#          weight: 500
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
