name: sahibindenmobile
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  flutter_switch: ^0.3.2
  responsive_grid_list: ^1.4.0
  dio: ^5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
