@echo off
    type nul > img_arrow_down.svg
    type nul > img_arrow_left.svg
    type nul > img_arrow_right.svg
    type nul > img_arrow_up.svg
    type nul > img_bag.svg
    type nul > img_checkmark.svg
    type nul > img_close.svg
    type nul > img_contrast.svg
    type nul > img_contrast_gray_400.svg
    type nul > img_download.svg
    type nul > img_facebook.svg
    type nul > img_favorite.svg
    type nul > img_favorite_blue_gray_800.svg
    type nul > img_favorite_primary.svg
    type nul > img_floating_icon.svg
    type nul > img_floating_icon_primary.svg
    type nul > img_frame.svg
    type nul > img_frame_1.svg
    type nul > img_frame_50x50.svg
    type nul > img_frame_onprimary.svg
    type nul > img_frame_primary.svg
    type nul > img_frame_primary_20x20.svg
    type nul > img_frame_primary_24x24.svg
    type nul > img_frame_primary_50x50.svg
    type nul > img_google.svg
    type nul > img_heroicons_arrow_up_20_solid.svg
    type nul > img_heroicons_arrow_up_20_solid_onprimary.svg
    type nul > img_home.svg
    type nul > img_icbaselinewaterdrop.svg
    type nul > img_linkedin.svg
    type nul > img_linkedin_blue_gray_800_03.svg
    type nul > img_linkedin_blue_gray_800_05.svg
    type nul > img_linkedin_deep_orange_a200.svg
    type nul > img_location.svg
    type nul > img_lock.svg
    type nul > img_lock_blue_gray_800.svg
    type nul > img_lock_onprimary.svg
    type nul > img_lock_onprimary_20x20.svg
    type nul > img_menu.svg
    type nul > img_rewind.svg
    type nul > img_rewind_blue_gray_800.svg
    type nul > img_settings.svg
    type nul > img_signal.svg
    type nul > img_television.svg
    type nul > img_television_primary.svg
    type nul > img_television_primary_20x20.svg
    type nul > img_thumbs_up.svg
    type nul > img_user.svg
    type nul > img_user_onprimary.svg
    type nul > img_video_camera.svg